apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demokubeapi
  name: demokubeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demokubeapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demokubeapi
    spec:
      containers:
      - image: docker.io/mperedo/democore6api
        name: demokubeapi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
status: {}