pipeline {
  agent any
  stages {
    stage('clone repository') {
      steps {
        sh '''
git --version'''
      }
    }

    stage('Deploy billing App') {
      steps {
        withCredentials(bindings: [
                      string(credentialsId: 'kubernete-jenkis-server-account', variable: 'api_token')
                      ]) {
            sh 'kubectl --token $api_token --server https://host.docker.internal:63679 --insecure-skip-tls-verify=true apply -f ./DemoCore6API/deploy-jenkins.yml'
          }

        }
      }

    }
  }