apiVersion: v1
kind: Service
metadata:
  name: demokubeapi
  labels:
    run: demokubeapi
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 80
  selector:
    app: demokubeapi
  type: NodePort